// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAyeI83EDEUU8QqU-megMkOTFllMww6To',
    appId: '1:884831250141:web:eae5d0ef473bf64c935d34',
    messagingSenderId: '884831250141',
    projectId: 'cherpapp-8bc95',
    authDomain: 'cherpapp-8bc95.firebaseapp.com',
    storageBucket: 'cherpapp-8bc95.appspot.com',
    measurementId: 'G-0PGB5NZXKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxDgPtje_u8vkOBWkDQWm_uuLN0qrkMzE',
    appId: '1:884831250141:android:9c0a25fd32c4db78935d34',
    messagingSenderId: '884831250141',
    projectId: 'cherpapp-8bc95',
    storageBucket: 'cherpapp-8bc95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyUpM4-r-bz4UOBQ6kZN-UmvxeRD7MLS8',
    appId: '1:884831250141:ios:36de93a79d7c4cd8935d34',
    messagingSenderId: '884831250141',
    projectId: 'cherpapp-8bc95',
    storageBucket: 'cherpapp-8bc95.appspot.com',
    iosClientId: '884831250141-ju21bvbjeoto6hhlp92gisgle4ter7hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyUpM4-r-bz4UOBQ6kZN-UmvxeRD7MLS8',
    appId: '1:884831250141:ios:36de93a79d7c4cd8935d34',
    messagingSenderId: '884831250141',
    projectId: 'cherpapp-8bc95',
    storageBucket: 'cherpapp-8bc95.appspot.com',
    iosClientId: '884831250141-ju21bvbjeoto6hhlp92gisgle4ter7hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherpApp',
  );
}
